source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               avatar.jpg,\
               OSGI-INF/,\
               index.html,\
               wc/,\
               index.jsp,\
               taglibs-standard-impl-1.2.5.fixed.jar,\
               taglibs-standard-spec-1.2.5.jar
