#Product Runtime Configuration File
osgi.bundles.defaultStartLevel=4
osgi.bundles=javax.el@start,\
  javax.servlet.jsp@start,\
  javax.xml@start,\
  org.apache.commons.fileupload@start,\
  org.apache.commons.io@start,\
  org.apache.commons.logging@start,\
  org.apache.felix.gogo.command@start,\
  org.apache.felix.gogo.runtime@start,\
  org.apache.felix.gogo.shell@start,\
  org.apache.felix.webconsole@start,\
  org.apache.jasper.glassfish@start,\
  org.eclipse.equinox.common@start,\
  org.eclipse.equinox.console@start,\
  org.eclipse.equinox.http.helper@start,\
  org.eclipse.equinox.http.registry@start,\
  org.eclipse.equinox.servletbridge.extensionbundle,\
  org.eclipse.equinox.http.servlet@start,\
  org.eclipse.equinox.http.servletbridge@start,\
  org.eclipse.equinox.jsp.jasper@start,\
  org.eclipse.equinox.jsp.jasper.registry@start,\
  org.eclipse.equinox.registry@start,\
  org.eclipse.equinox.servletbridge@start,\
  org.eclipse.osgi.services@start,\
  org.eclipse.osgi.util@start,\
  sample.http@start,\
  sample.res@start,\
  org.eclipse.equinox.region,\
  org.eclipse.equinox.transforms.hook,\
  org.eclipse.equinox.weaving.hook,\
  org.eclipse.osgi.compatibility.state
