source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               helloworld.html
additional.bundles = org.eclipse.osgi,\
                     jakarta.servlet-api
