source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               plugin.properties
additional.bundles = javax.servlet,\
                     org.eclipse.osgi,\
                     org.eclipse.osgi.services
