source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               avatar.jpg,\
               index.html,\
               plugin.xml,\
               wc/,\
               index.jsp,\
               taglibs-standard-impl-1.2.5.fixed.jar,\
               taglibs-standard-spec-1.2.5.jar
source../ = src/
additional.bundles = org.eclipse.osgi,\
                     org.eclipse.osgi.services,\
                     javax.servlet

